name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Se ejecuta todos los días
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: vjLarios
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit snake
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
